In [ ]:
from keras import Sequential

In [ ]:
from keras.layers import Dense, SimpleRNN

In [ ]:
model = Sequential()

In [ ]:
model.add(SimpleRNN(3, input_shape=(4, 5))) # 4 is the length of word(max) 5 is the total vocab
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 27        
                                                                 
 dense (Dense)               (None, 1)                 4         
                                                                 
Total params: 31 (124.00 Byte)
Trainable params: 31 (124.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.get_weights()

[array([[-0.05525291,  0.05311567,  0.21823078],
        [-0.5753267 , -0.48160818,  0.13537484],
        [ 0.427635  , -0.15691328, -0.11925983],
        [-0.3206585 ,  0.7170226 ,  0.57352513],
        [ 0.7194541 ,  0.5819071 , -0.26035863]], dtype=float32),
 array([[ 0.55340636, -0.6954879 , -0.4582989 ],
        [ 0.7423261 ,  0.16229478,  0.6500864 ],
        [-0.37774774, -0.6999692 ,  0.60609376]], dtype=float32),
 array([0., 0., 0.], dtype=float32),
 array([[ 0.45949197],
        [-0.5714072 ],
        [ 0.43289638]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
model.get_weights()[0]

array([[-0.05525291,  0.05311567,  0.21823078],
       [-0.5753267 , -0.48160818,  0.13537484],
       [ 0.427635  , -0.15691328, -0.11925983],
       [-0.3206585 ,  0.7170226 ,  0.57352513],
       [ 0.7194541 ,  0.5819071 , -0.26035863]], dtype=float32)

In [ ]:
from keras.datasets import imdb

In [ ]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

In [ ]:
X_train[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 22665,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 21631,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 19193,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 10311,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 31050,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 12118,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5

In [ ]:
X_train.shape

(25000,)

In [ ]:
import numpy as np

sent = [
    "Argentina won worldcup",
    "messi played very well",
    "above all is my imagination",
    "definitely we gonna win next worldcup"
]

In [ ]:
from keras.preprocessing.text import Tokenizer # integer encoding

In [ ]:
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(sent)

In [ ]:
tokenizer.word_index

{'worldcup': 1,
 'argentina': 2,
 'won': 3,
 'messi': 4,
 'played': 5,
 'very': 6,
 'well': 7,
 'above': 8,
 'all': 9,
 'is': 10,
 'my': 11,
 'imagination': 12,
 'definitely': 13,
 'we': 14,
 'gonna': 15,
 'win': 16,
 'next': 17}

In [ ]:
tokenizer.word_counts

OrderedDict([('argentina', 1),
             ('won', 1),
             ('worldcup', 2),
             ('messi', 1),
             ('played', 1),
             ('very', 1),
             ('well', 1),
             ('above', 1),
             ('all', 1),
             ('is', 1),
             ('my', 1),
             ('imagination', 1),
             ('definitely', 1),
             ('we', 1),
             ('gonna', 1),
             ('win', 1),
             ('next', 1)])

In [ ]:
tokenizer.document_count

4

In [ ]:
encoding = tokenizer.texts_to_sequences(sent)

In [ ]:
encoding

[[2, 3, 1], [4, 5, 6, 7], [8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 1]]

In [ ]:
from keras.utils import pad_sequences # using padding to make every sequence as same size

In [ ]:
pad_sequences(encoding, padding='post')

array([[ 2,  3,  1,  0,  0,  0],
       [ 4,  5,  6,  7,  0,  0],
       [ 8,  9, 10, 11, 12,  0],
       [13, 14, 15, 16, 17,  1]], dtype=int32)

In [ ]:
y_train

array([1, 0, 0, ..., 0, 1, 0])

In [ ]:
len(X_train[0])

218

taking minimum length -- if taking maximum length then paddin is required

In [ ]:
myList = []
for i in X_train:
    myList.append(len(i))

min(myList)

11

too low -- padding is required

In [ ]:
X_train = pad_sequences(X_train, padding = 'post', maxlen = 50)

In [ ]:
X_test = pad_sequences(X_test, padding='post', maxlen=50)

In [ ]:
model = Sequential()

In [ ]:
model.add(SimpleRNN(32, input_shape = (50, 1)))

In [ ]:
model.add(Dense(1, activation='sigmoid'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 32)                1088      
                                                                 
 dense_1 (Dense)             (None, 1)                 33        
                                                                 
Total params: 1121 (4.38 KB)
Trainable params: 1121 (4.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.compile(loss='binary_crossentropy',
              optimizer = 'adam',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train,
          validation_data= (X_test, y_test),
          epochs=5)

Epoch 1/5
782/782 [==============================] - 15s 17ms/step - loss: 0.7150 - accuracy: 0.5083 - val_loss: 0.6940 - val_accuracy: 0.5068
Epoch 2/5
782/782 [==============================] - 13s 17ms/step - loss: 0.6930 - accuracy: 0.5081 - val_loss: 0.6943 - val_accuracy: 0.5011
Epoch 3/5
782/782 [==============================] - 11s 15ms/step - loss: 0.6930 - accuracy: 0.5040 - val_loss: 0.6953 - val_accuracy: 0.5024
Epoch 4/5
782/782 [==============================] - 15s 19ms/step - loss: 0.6925 - accuracy: 0.5049 - val_loss: 0.6938 - val_accuracy: 0.5019
Epoch 5/5
782/782 [==============================] - 11s 14ms/step - loss: 0.6927 - accuracy: 0.5104 - val_loss: 0.6939 - val_accuracy: 0.5004


In [ ]:
model.predict(X_test)

782/782 [==============================] - 5s 6ms/step


array([[0.4955257],
       [0.4955257],
       [0.4955257],
       ...,
       [0.4955257],
       [0.4955257],
       [0.4955257]], dtype=float32)